# Generated by scripts/terraform-import-yc.sh.
# Review this file after import. lifecycle.ignore_changes is intentional for
# the first import pass; remove it resource by resource after the HCL matches YC.

resource "yandex_container_registry" "app" {
  name      = "vizitka"
  folder_id = var.folder_id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_network" "main" {
  name      = "default"
  folder_id = var.folder_id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_subnet" "main" {
  name           = "default-ru-central1-a"
  folder_id      = var.folder_id
  zone           = "ru-central1-a"
  network_id     = yandex_vpc_network.main.id
  v4_cidr_blocks = ["10.128.0.0/24"]

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_iam_service_account" "coi_puller" {
  name      = "coi-puller"
  folder_id = var.folder_id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_security_group" "sg_0" {
  name       = "default-sg-enp1efpq841kemvnbc5h"
  folder_id  = var.folder_id
  network_id = yandex_vpc_network.main.id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_security_group" "app_managed" {
  count = var.manage_app_security_group ? 1 : 0

  name       = var.app_security_group_name
  folder_id  = var.folder_id
  network_id = yandex_vpc_network.main.id

  ingress {
    description    = "HTTP"
    protocol       = "TCP"
    port           = 80
    v4_cidr_blocks = var.app_http_cidr_blocks
  }

  ingress {
    description    = "HTTPS"
    protocol       = "TCP"
    port           = 443
    v4_cidr_blocks = var.app_https_cidr_blocks
  }

  dynamic "ingress" {
    for_each = length(var.app_ssh_cidr_blocks) > 0 ? [1] : []

    content {
      description    = "SSH"
      protocol       = "TCP"
      port           = 22
      v4_cidr_blocks = var.app_ssh_cidr_blocks
    }
  }

  egress {
    description    = "Outbound"
    protocol       = "ANY"
    v4_cidr_blocks = var.app_egress_cidr_blocks
  }
}

locals {
  app_security_group_ids = var.manage_app_security_group ? yandex_vpc_security_group.app_managed[*].id : [yandex_vpc_security_group.sg_0.id]
}

resource "yandex_compute_instance" "app" {
  name                      = var.app_vm_name
  folder_id                 = var.folder_id
  zone                      = var.app_zone
  platform_id               = var.app_platform_id
  allow_stopping_for_update = true
  service_account_id        = yandex_iam_service_account.coi_puller.id

  resources {
    cores         = var.app_cores
    memory        = var.app_memory_gb
    core_fraction = var.app_core_fraction
  }

  boot_disk {
    disk_id     = "fhmkvhrnek1nsba7ug3d"
    auto_delete = true
  }

  network_interface {
    subnet_id          = yandex_vpc_subnet.main.id
    nat                = var.app_enable_nat
    ip_address         = var.app_private_ip
    security_group_ids = local.app_security_group_ids
  }

  lifecycle {
    ignore_changes = [
      boot_disk,
      description,
      labels,
      metadata,
    ]
  }
}
