# Generated by scripts/terraform-import-yc.sh.
# Review this file after import. lifecycle.ignore_changes is intentional for
# the first import pass; remove it resource by resource after the HCL matches YC.

resource "yandex_container_registry" "app" {
  name      = "vizitka"
  folder_id = var.folder_id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_network" "main" {
  name      = "default"
  folder_id = var.folder_id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_subnet" "main" {
  name           = "default-ru-central1-a"
  folder_id      = var.folder_id
  zone           = "ru-central1-a"
  network_id     = yandex_vpc_network.main.id
  v4_cidr_blocks = ["10.128.0.0/24"]

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_iam_service_account" "coi_puller" {
  name      = "coi-puller"
  folder_id = var.folder_id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_vpc_security_group" "sg_0" {
  name       = "default-sg-enp1efpq841kemvnbc5h"
  folder_id  = var.folder_id
  network_id = yandex_vpc_network.main.id

  lifecycle {
    ignore_changes = all
  }
}

resource "yandex_compute_instance" "app" {
  name                      = "vizitka-coi"
  folder_id                 = var.folder_id
  zone                      = "ru-central1-a"
  platform_id               = "standard-v3"
  allow_stopping_for_update = true
  service_account_id        = yandex_iam_service_account.coi_puller.id

  resources {
    cores         = 2
    memory        = 2
    core_fraction = 100
  }

  boot_disk {
    disk_id     = "fhmkvhrnek1nsba7ug3d"
    auto_delete = true
  }

  network_interface {
    subnet_id          = yandex_vpc_subnet.main.id
    nat                = true
    ip_address         = "10.128.0.15"
    security_group_ids = [yandex_vpc_security_group.sg_0.id]
  }

  lifecycle {
    ignore_changes = all
  }
}
